In [1]:
import numpy as np
a = np.arange((10, 10))
a

TypeError: arange: scalar arguments expected instead of a tuple.

In [ ]:
np.where(a < 5)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
        6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [11]:
import torch

pt = torch.tensor([[
    [
    [0.7, 0.8],
    [0.5, 0.4]
    ],
    [
    [0.9, 0.4],
    [0.5, 0.2]
    ],
                   ]]).float()
gt = torch.tensor([[
    [
    [1, 0],
    [1, 1]
    ],
    [
    [1, 1],
    [1, 1]
    ],
                   ]]).float()

In [12]:
from torch.nn import Sigmoid, BCELoss

m = Sigmoid()
bce = BCELoss(reduction="sum")
print(gt)
# loss = gt * torch.log(pt) * (1 - pt) ** 2
loss = bce(pt, gt)
print(loss)
loss = gt * torch.log(pt) 
print(loss)



tensor([[[[1., 0.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
tensor(6.8998)
tensor([[[[-0.3567, -0.0000],
          [-0.6931, -0.9163]],

         [[-0.1054, -0.9163],
          [-0.6931, -1.6094]]]])


In [4]:
import torch.nn.functional as F

F.cross_entropy(a, b)

NameError: name 'a' is not defined