In [2]:
import torch

pt = torch.tensor([[
    [
    [0.7, 0.8],
    [0.5, 0.4],
    [0.5, 0.4],
    ],
    [
    [0.2, 0.4],
    [0.5, 0.2],
    [0.5, 0.4],
    ],
                   ]]).float()
gt = torch.tensor([[
    [
    [1, 0],
    [1, 1],
    [1, 1]
    ],
    [
    [1, 1],
    [1, 1],
    [1, 1]
    ],
                   ]], dtype=torch.uint8)

In [3]:
from torch.nn import Sigmoid, BCELoss

m = Sigmoid()
bce = BCELoss(reduction='none')
print(gt)
# loss = gt * torch.log(pt) * (1 - pt) ** 2
# loss = bce(pt, gt).mean()
# print(loss)
# loss = gt * torch.log(pt) 
# print(loss)



tensor([[[[1, 0],
          [1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1],
          [1, 1]]]], dtype=torch.uint8)


In [4]:
pt

tensor([[[[0.7000, 0.8000],
          [0.5000, 0.4000],
          [0.5000, 0.4000]],

         [[0.2000, 0.4000],
          [0.5000, 0.2000],
          [0.5000, 0.4000]]]])

In [5]:
pt.shape

torch.Size([1, 2, 3, 2])

In [7]:
# import torch.nn.functional as F

# F.
a = [1,2,3]
b = [4,5,6]

c = list(zip(a, b))

In [8]:
for i in c:
    print(i)

(1, 4)
(2, 5)
(3, 6)


In [9]:
for i in c:
    print(i)

(1, 4)
(2, 5)
(3, 6)


In [27]:
import segmentation_models_pytorch as smp


# first compute statistics for true positives, false positives, false negative and
# true negative "pixels"
tp, fp, fn, tn = smp.metrics.get_stats(pt, gt, mode='multilabel', threshold=0.5)

# then compute metrics with required reduction (see metric docs)
iou_score = smp.metrics.iou_score(tp, fp, fn, tn, reduction="none",)
f1_score = smp.metrics.f1_score(tp, fp, fn, tn, reduction="none")
f2_score = smp.metrics.fbeta_score(tp, fp, fn, tn, beta=2, reduction="micro")
accuracy = smp.metrics.accuracy(tp, fp, fn, tn, reduction="macro")
recall = smp.metrics.recall(tp, fp, fn, tn, reduction="micro-imagewise")

In [28]:
tp

tensor([[3, 2]])

In [18]:
iou_score

tensor([[0.5000, 0.3333]])

In [19]:
f1_score

tensor([[0.6667, 0.5000]])

In [20]:
accuracy


tensor(0.4167)

In [21]:
tp

tensor([[3, 2]])

In [3]:
import torch

# Load the checkpoint
checkpoint_path = "/home/treerspeaking/src/python/hand_seg/logs/hand_segmentation/version_10/checkpoints/best_hand_segmentation_epoch=99_val/epoch_iou=0.8445.ckpt"

# Load checkpoint
checkpoint = torch.load(checkpoint_path, map_location='cpu')

print("=== Checkpoint Keys ===")
for key in checkpoint.keys():
    print(f"- {key}")

print("\n=== State Dict Keys (Model Weights) ===")
if 'state_dict' in checkpoint:
    state_dict = checkpoint['state_dict']
    for key in state_dict.keys():
        print(f"- {key}: {state_dict[key].shape}")

print("\n=== Hyperparameters ===")
if 'hyper_parameters' in checkpoint:
    hyper_params = checkpoint['hyper_parameters']
    for key, value in hyper_params.items():
        print(f"- {key}: {value}")

print("\n=== Other Checkpoint Info ===")
for key in checkpoint.keys():
    if key not in ['state_dict', 'hyper_parameters']:
        value = checkpoint[key]
        if isinstance(value, (int, float, str, bool)):
            print(f"- {key}: {value}")
        elif isinstance(value, dict):
            print(f"- {key}: {type(value)} with {len(value)} items")
        else:
            print(f"- {key}: {type(value)}")

=== Checkpoint Keys ===
- epoch
- global_step
- pytorch-lightning_version
- state_dict
- loops
- callbacks
- optimizer_states
- lr_schedulers
- MixedPrecision
- hparams_name
- hyper_parameters

=== State Dict Keys (Model Weights) ===
- model.backbone.low_level_features.0.0.weight: torch.Size([32, 3, 3, 3])
- model.backbone.low_level_features.0.1.weight: torch.Size([32])
- model.backbone.low_level_features.0.1.bias: torch.Size([32])
- model.backbone.low_level_features.0.1.running_mean: torch.Size([32])
- model.backbone.low_level_features.0.1.running_var: torch.Size([32])
- model.backbone.low_level_features.0.1.num_batches_tracked: torch.Size([])
- model.backbone.low_level_features.1.conv.0.0.weight: torch.Size([32, 1, 3, 3])
- model.backbone.low_level_features.1.conv.0.1.weight: torch.Size([32])
- model.backbone.low_level_features.1.conv.0.1.bias: torch.Size([32])
- model.backbone.low_level_features.1.conv.0.1.running_mean: torch.Size([32])
- model.backbone.low_level_features.1.conv.0.1

In [43]:
from train import DeepLabLightningModule, HandSegDataModule

In [47]:
a = HandSegDataModule("./dataset/new_dataset", 24, 24, None, None, None)

In [50]:
a.train.mask_folders

['masks_hand_signature', 'masks_seal']